-- Net-new AI companies discovered 2026-06-29 (probed live on greenhouse/ashby/lever).
-- 31 with open senior roles now, 29 board-valid (0 senior today).
insert into public.companies (name, slug, ats_provider, source) values
  ('CoreWeave','coreweave','greenhouse','discovered'),
  ('Crusoe','crusoe','ashby','discovered'),
  ('Chainguard','chainguard','greenhouse','discovered'),
  ('Mercor','mercor','ashby','discovered'),
  ('Ambience Healthcare','ambiencehealthcare','ashby','discovered'),
  ('Together AI','togetherai','greenhouse','discovered'),
  ('Baseten','baseten','ashby','discovered'),
  ('Hex','hextechnologies','greenhouse','discovered'),
  ('Cresta','cresta','greenhouse','discovered'),
  ('Reflection AI','reflectionai','ashby','discovered'),
  ('Snorkel AI','snorkelai','greenhouse','discovered'),
  ('Semgrep','semgrep','ashby','discovered'),
  ('Commure','commure','ashby','discovered'),
  ('Cartesia','cartesia','ashby','discovered'),
  ('Drata','drata','ashby','discovered'),
  ('Physical Intelligence','physicalintelligence','ashby','discovered'),
  ('Waabi','waabi','lever','discovered'),
  ('Modal','modal','ashby','discovered'),
  ('Anyscale','anyscale','ashby','discovered'),
  ('Lightning AI','lightningai','greenhouse','discovered'),
  ('Speak','speak','ashby','discovered'),
  ('Cognition','cognition','ashby','discovered'),
  ('Fireworks AI','fireworksai','greenhouse','discovered'),
  ('Render','render','ashby','discovered'),
  ('Neon','neon','ashby','discovered'),
  ('Column','column','ashby','discovered'),
  ('Galileo','galileo','greenhouse','discovered'),
  ('Braintrust','braintrust','ashby','discovered'),
  ('Thinking Machines Lab','thinkingmachines','greenhouse','discovered'),
  ('Figure','figure','greenhouse','discovered'),
  ('Runway','runway','ashby','discovered'),
  ('Lambda','lambda','ashby','discovered'),
  ('Weaviate','weaviate','ashby','discovered'),
  ('Imbue','imbue','greenhouse','discovered'),
  ('Poolside','poolside','ashby','discovered'),
  ('Writer','writer','ashby','discovered'),
  ('Suki','suki','greenhouse','discovered'),
  ('OpenEvidence','openevidence','ashby','discovered'),
  ('LiveKit','livekit','ashby','discovered'),
  ('Observe.AI','observeai','greenhouse','discovered'),
  ('Railway','railway','ashby','discovered'),
  ('PlanetScale','planetscale','greenhouse','discovered'),
  ('Resend','resend','ashby','discovered'),
  ('Inngest','inngest','ashby','discovered'),
  ('Trigger.dev','triggerdev','ashby','discovered'),
  ('Zed','zed','ashby','discovered'),
  ('Warp','warp','greenhouse','discovered'),
  ('Lithic','lithic','greenhouse','discovered'),
  ('Modern Treasury','moderntreasury','ashby','discovered'),
  ('Labelbox','labelbox','greenhouse','discovered'),
  ('Comet','comet','greenhouse','discovered'),
  ('Replicant','replicant','ashby','discovered'),
  ('World Labs','worldlabs','greenhouse','discovered'),
  ('Cobot','cobot','ashby','discovered'),
  ('Sereact','sereact','ashby','discovered'),
  ('Distyl AI','distyl','ashby','discovered'),
  ('Dust','dust','ashby','discovered'),
  ('Tavus','tavus','ashby','discovered'),
  ('Synthflow','synthflow','ashby','discovered'),
  ('Pika','pika','ashby','discovered')
on conflict (slug) do nothing;